## name: Anime
## blurb: A vibrant, colorful pastel theme

foreground               #e4dcf4
background               #1a1829
selection_foreground     #e4dcf4
selection_background     #42385c

cursor                   #ff8da1
cursor_text_color        #1a1829

url_color                #e4a3fa

active_tab_foreground    #1a1829
active_tab_background    #8bb8f8
inactive_tab_foreground  #a49cb5
inactive_tab_background  #242036

active_border_color      #e4a3fa
inactive_border_color    #312c47

# black
color0   #242036
color8   #42385c

# red
color1   #ff8da1
color9   #ff8da1

# green
color2   #a1eebb
color10  #a1eebb

# yellow
color3   #f6d288
color11  #f6d288

# blue
color4   #8bb8f8
color12  #8bb8f8

# magenta
color5   #e4a3fa
color13  #e4a3fa

# cyan
color6   #94e7e6
color14  #94e7e6

# white
color7   #e4dcf4
color15  #f0e8fa
