## name: Cyberpunk
## blurb: High-contrast neon colors for a futuristic Night City aesthetic

foreground               #c2cce6
background               #090014
selection_foreground     #090014
selection_background     #00ffff

cursor                   #ff007f
cursor_text_color        #090014

url_color                #bc13fe

active_tab_foreground    #090014
active_tab_background    #00ff41
inactive_tab_foreground  #744b9e
inactive_tab_background  #180a2b

active_border_color      #bc13fe
inactive_border_color    #180a2b

# black
color0   #180a2b
color8   #4c3272

# red (Neon Pink)
color1   #ff007f
color9   #ff007f

# green (Matrix Green)
color2   #00ff41
color10  #00ff41

# yellow (Cyber Yellow)
color3   #e5ff00
color11  #e5ff00

# blue (Neon Blue)
color4   #0033ff
color12  #0033ff

# magenta (Neon Purple)
color5   #bc13fe
color13  #bc13fe

# cyan (Neon Cyan)
color6   #00ffff
color14  #00ffff

# white
color7   #c2cce6
color15  #ffffff
