# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282828"

# Main text color
theme[main_fg]="#ebdbb2"

# Title color for boxes
theme[title]="#a89984"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#fabd2f"

# Background color of selected item in processes box
theme[selected_bg]="#504945"

# Foreground color of selected item in processes box
theme[selected_fg]="#fe8019"

# Color of inactive/disabled text
theme[inactive_fg]="#928374"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#ebdbb2"

# Background color of the percentage meters
theme[meter_bg]="#3c3836"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d3869b"

# Cpu box outline color
theme[cpu_box]="#b8bb26"

# Memory/disks box outline color
theme[mem_box]="#fabd2f"

# Net up/down box outline color
theme[net_box]="#83a598"

# Processes box outline color
theme[proc_box]="#fb4934"

# Box divider line and small boxes line color
theme[div_line]="#665c54"

# Temperature graph colors
theme[temp_start]="#b8bb26"
theme[temp_mid]="#fabd2f"
theme[temp_end]="#fb4934"

# CPU graph colors
theme[cpu_start]="#b8bb26"
theme[cpu_mid]="#fabd2f"
theme[cpu_end]="#fb4934"

# Mem/Disk free meter
theme[free_start]="#b8bb26"
theme[free_mid]="#b8bb26"
theme[free_end]="#b8bb26"

# Mem/Disk cached meter
theme[cached_start]="#83a598"
theme[cached_mid]="#83a598"
theme[cached_end]="#83a598"

# Mem/Disk available meter
theme[available_start]="#d3869b"
theme[available_mid]="#d3869b"
theme[available_end]="#d3869b"

# Mem/Disk used meter
theme[used_start]="#fb4934"
theme[used_mid]="#fb4934"
theme[used_end]="#fb4934"

# Download graph colors
theme[download_start]="#83a598"
theme[download_mid]="#8ec07c"
theme[download_end]="#8ec07c"

# Upload graph colors
theme[upload_start]="#fb4934"
theme[upload_mid]="#fe8019"
theme[upload_end]="#fabd2f"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#83a598"
theme[process_mid]="#8ec07c"
theme[process_end]="#8ec07c"
