########################
## Font Configuration ##
########################

font_family       CaskaydiaCove Nerd Font Mono 
bold_font         auto
italic_font       auto
bold_italic_font  auto

font_size 10.5

dynamic_background_opacity yes
background_opacity 0.85

##########################
## Cursor Configuration ##
##########################
# cursor #cccccc
cursor_shape block
cursor_blink_interval 0
cursor_bar_thickness 2.0

# cursor_underline_thickness 2.0

cursor_trail 5
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
# cursor_trail_color none

#############################
## scrollbar Configuration ##
#############################


scrollbar never

#: Control when the scrollbar is displayed.

#: scrolled
#:     means when the scrolling backwards has started.
#: hovered
#:     means when the mouse is hovering on the right edge of the window.
#: scrolled-and-hovered
#:     means when the mouse is over the scrollbar region *and* scrolling backwards has started.
#: always
#:     means whenever any scrollback is present
#: never
#:     means disable the scrollbar.

# scrollbar_interactive yes

##########################
## Window Configuration ##
##########################
remeber_window_size no 
initial_window_width 640
initial_window_height 480
window_padding_width 20

#############
### Extra ###
#############
url_style curly
confirm_os_window_close 0

enabled_layouts splits,stack

###############
##Keybindings##
###############
#
############
##Themings##
############

# BEGIN_KITTY_THEME
# Rosé Pine
include colors.conf
# END_KITTY_THEME
